# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052d9312b2b982720dccf0f4667ab125484e1336d9ad02a51ac294affe48ed86f1ddc4550027ac02179c813a90eea0db1f83c2068c0f57c1dc17302651fb4438

test:
  secret_key_base: 77e69271b9cdc608a8a44dd9bbc187eb0066006285265a079349b994cb04d6f49cebe35fda8f1fba03bb68303cb582541719c3cd5b32114026a800a74d34b560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
